// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApctxFQvWdGopIsQQSlz3XRIvLcGQEL9M',
    appId: '1:404065412028:web:e5e6408ca3ec12917f01b9',
    messagingSenderId: '404065412028',
    projectId: 'dialyease-e42ac',
    authDomain: 'dialyease-e42ac.firebaseapp.com',
    storageBucket: 'dialyease-e42ac.firebasestorage.app',
    measurementId: 'G-7R330CJ8F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs0kABmgA-eruVjNAdD6fDdTFoK6_5ars',
    appId: '1:404065412028:android:f9c2252cc3a14ce97f01b9',
    messagingSenderId: '404065412028',
    projectId: 'dialyease-e42ac',
    storageBucket: 'dialyease-e42ac.firebasestorage.app',
  );
}
